main:
  - name: "Posts"
    url: /posts/
    weight: 1
  - name: "About"
    url: /about/
    weight: 2
  - name: "Projects"
    url: /projects/
    weight: 3
  #- name: "Talks"
  #  url: /talks/
  #  weight: 4
  #- name: "Artwork"
  #  url: /gallery/
  #  weight: 5

footer:
  - name: "Posts"
    url: /posts/
    weight: 1
  - name: "About"
    url: /about/
    weight: 2
  - name: "Projects"
    url: /projects/
    weight: 3
  #- name: "Talks"
  #  url: /talks/
  #  weight: 4
  #- name: "Artwork"
  #  url: /gallery/
  #  weight: 5


bottom:
  - name: "RSS"
    url: /index.xml
    weight: 1
  #- name: "JSON"
  #  url: /index.json
  #  weight: 3
