main:
  - name: "Posts"
    url: /posts/
    weight: 1
  - name: "Projects"
    url: /projects/
    weight: 2
  - name: "Talks"
    url: /talks/
    weight: 3
  - name: "Artwork"
    url: /gallery/
    weight: 4

footer:
  - name: "Posts"
    url: /posts/
    weight: 1
  - name: "Projects"
    url: /projects/
    weight: 2
  - name: "Talks"
    url: /talks/
    weight: 3
  - name: "Artwork"
    url: /gallery/
    weight: 4


bottom:
  - name: "Privacy Policy"
    url: /privacy-policy/
    weight: 1
  - name: "RSS"
    url: /index.xml
    weight: 1
  - name: "Atom"
    url: /atom.xml
    weight: 2
  - name: "JSON"
    url: /index.json
    weight: 3
