description: "The Hacking and Coffee blog"
copyrightHolder: "Hacking & Coffee"

show_featured_image_in_list: false  # Set to true to show featured images in list view or recent posts (default: false)

hero:
  image: ""
  title: "Hacking and Coffee"
  subtitle: "The Hacking and Coffee blog"

contactData:
  email: ""
